[mysql]
uri = "root:123456@tcp(127.0.0.1:3306)/hi-nature-250826?charset=utf8&timeout=30s"

[mssql]
uri = "sqlserver://sa:Nature123!@127.0.0.1?database=hi-nature-250826&connection+timeout=30"

[mongodb]
uri = "mongodb://admin:123456@127.0.0.1:27018/hi-nature-250826?replicaSet=rs0&authSource=admin"

[redis]
host = "127.0.0.1"
port = 6379
password = "123456"
timeout = 10000     # 毫秒

[rabbitmq]
address = "amqp://admin:123456@127.0.0.1:5672/yq"

[consul]
host = "127.0.0.1"
port = 8500
secure = false
health_check = "/service/healthCheck"
health_check_interval = 10              # 秒
health_check_timeout = 5                # 秒
deregister_critical_service_after = 600 # 秒

[logger]
default = "console"

[dev]
developer = "dev"
